campanias:
    path:     /
    defaults: { _controller: "CampaniasBundle:Campania:index" }

campanias_show:
    path:     /{id}/show
    defaults: { _controller: "CampaniasBundle:Campania:show" }

campanias_new:
    path:     /new
    defaults: { _controller: "CampaniasBundle:Campania:new" }

campanias_create:
    path:     /create
    defaults: { _controller: "CampaniasBundle:Campania:create" }
    requirements: { _method: post }

campanias_edit:
    path:     /{id}/edit
    defaults: { _controller: "CampaniasBundle:Campania:edit" }

campanias_update:
    path:     /{id}/update
    defaults: { _controller: "CampaniasBundle:Campania:update" }
    requirements: { _method: post|put }

campanias_delete:
    path:     /{id}/delete
    defaults: { _controller: "CampaniasBundle:Campania:delete" }
    requirements: { _method: post|delete }
