resultado_cabecera:
    path:     /
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:index" }

resultado_cabecera_show:
    path:     /{id}/show
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:show" }

resultado_cabecera_new:
    path:     /new
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:new" }

resultado_cabecera_create:
    path:     /create
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:create" }
    requirements: { _method: post }

resultado_cabecera_edit:
    path:     /{id}/edit
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:edit" }

resultado_cabecera_update:
    path:     /{id}/update
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:update" }
    requirements: { _method: post|put }

resultado_cabecera_delete:
    path:     /{id}/delete
    defaults: { _controller: "CampaniasBundle:ResultadoCabecera:delete" }
    requirements: { _method: post|delete }
