<?php

namespace BigD\PersonasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository {

    public function getAcPersonas($filters = null) {
        $qb = $this->createQueryBuilder('p');

        if ($filters['nombre']) {

            $qb->andWhere('upper(p.nombre) LIKE upper(:nombre)')
                    ->setParameter('nombre', '%' . $filters['nombre'] . '%');
        }
        if ($filters['apellido']) {

            $qb->andWhere('upper(p.apellido) LIKE upper(:apellido)')
                    ->setParameter('apellido', '%' . $filters['apellido'] . '%');
        }
        if ($filters['numeroDocumento']) {

            $qb->andWhere('upper(p.numeroDocumento) LIKE upper(:numeroDocumento)')
                    ->setParameter('numeroDocumento', '%' . $filters['numeroDocumento'] . '%');
        }
        
        $qb->setMaxResults(1000);

        return $qb->getQuery()->getResult();
    }

}
