<?php

namespace BigD\CampaniasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaniaRepository extends EntityRepository {

    public function getByLike($string, $extraParam = null) {

        $em = $this->getEntityManager();

        $consulta = $em->createQuery('SELECT c
                                          FROM CampaniasBundle:Campania c
                                          WHERE upper(c.nombre) LIKE upper(:string)
                                     ');


        $consulta->setParameter('string', '%' . $string . '%');

        $return = $consulta->getArrayResult();

        return $return;
    }

}
