<?php

namespace BigD\CampaniasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultadoCabeceraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoCabeceraRepository extends EntityRepository
{
}
