<?php

namespace BigD\ElectoralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EstablecimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRepository extends EntityRepository
{
    public function getAcEstablecimientos($filters = null)
    {
        $qb = $this->createQueryBuilder('e');

        if ($filters['descripcion']) {

            $qb->andWhere('upper(e.descripcion) LIKE upper(:descripcion)')
                ->setParameter('descripcion', '%' . $filters['descripcion'] . '%');
        }
        if ($filters['codigo']) {

            $qb->andWhere('upper(e.codigo) LIKE upper(:codigo)')
                ->setParameter('codigo', '%' . $filters['codigo'] . '%');
        }


        $qb->setMaxResults(1000);

        return $qb->getQuery()->getResult();
    }
}
