parameters:
#    electoral.example.class: BigD\ElectoralBundle\Example

services:
#    electoral.example:
#        class: %electoral.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
