campanias_homepage:
    path:     /hello/{name}
    defaults: { _controller: CampaniasBundle:Default:index }

CampaniasBundle_campanias:
        resource: "@CampaniasBundle/Resources/config/routing/campania.yml"
        prefix:   /campanias

CampaniasBundle_campania_encuesta:
        resource: "@CampaniasBundle/Resources/config/routing/encuesta.yml"
        prefix:   /encuestas
        
CampaniasBundle_opciones_respuestas:
        resource: "@CampaniasBundle/Resources/config/routing/opciones_respuesta.yml"
        prefix:   /opciones_respuestas
        
CampaniasBundle_tipo_pregunta:
        resource: "@CampaniasBundle/Resources/config/routing/tipo_pregunta.yml"
        prefix:   /tipos_pregunta

CampaniasBundle_preguntas:
        resource: "@CampaniasBundle/Resources/config/routing/preguntas.yml"
        prefix:   /preguntas

CampaniasBundle_ajax:
        resource: "@CampaniasBundle/Resources/config/routing/ajax.yml"
        prefix:   /ajax
        
CampaniasBundle_resultado_cabecera:
        resource: "@CampaniasBundle/Resources/config/routing/resultadocabecera.yml"
        prefix:   /resultado_cabecera
