parameters:
#    campanias.example.class: BigD\CampaniasBundle\Example

services:
#    campanias.example:
#        class: %campanias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    manager.encuestas:
                class: BigD\CampaniasBundle\Services\EncuestasManager
                arguments:
                    container: '@service_container'
                tags:
                    - { name: manager.encuestas, alias: manager.encuestas }