parameters:
#    campanias.example.class: BigD\CampaniasBundle\Example

services:
#    campanias.example:
#        class: %campanias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
